=== rpavlik/vrjuggler-2.2-debs/modules/tweek/java/beanlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Tweek beanlist schema version 1.1 -->
<!-- $Id$ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="beanlist">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:choice>
          <xs:element name="service"  type="basicBean" />
          <xs:element name="viewer"   type="basicBean" />
          <xs:element name="guipanel" type="guiBean" />
          <xs:element name="generic"  type="basicBean" />
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Base type for all Beans. -->
  <xs:complexType name="basicBean">
    <xs:sequence>
      <xs:element name="file"         type="beanFile" />
      <xs:element name="dependencies" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:choice>
              <xs:element name="bean" type="xs:string" />
              <xs:element name="jar"  type="jarFile" />
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="guiBean">
    <xs:complexContent>
      <xs:extension base="basicBean">
        <xs:sequence>
          <xs:element name="tree">
            <xs:complexType>
              <xs:attribute name="path" type="treePath" use="optional"
                            default="/" />
            </xs:complexType>
          </xs:element>
          <xs:element name="icon" minOccurs="0">
            <xs:complexType>
              <xs:attribute name="source"  type="xs:anyURI" use="required" />
              <xs:attribute name="tooltip" type="xs:string" use="optional"
                            default="" />
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="beanFile">
    <xs:attribute name="name"  type="xs:string" use="required" />
    <xs:attribute name="class" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="jarFile">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="path" type="xs:string" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="treePath">
    <xs:restriction base="xs:string">
      <xs:pattern value="/(|\w[\w\s]*(/\w[\w\s]*)*)" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== rpavlik/vrjuggler-2.2-debs/modules/vrjuggler/vrjconfig/commoneditors/CommonEditors.xml
<?xml version="1.0" encoding="UTF-8"?>
<beanlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="http://www.vrjuggler.org/tweek/xsd/1.1/beanlist.xsd">
   <service name="PositionalDeviceEditor">
      <file name="${VJ_BASE_DIR}/${VJ_DATA_DIR}/java/CommonEditors.jar"
            class="org.vrjuggler.vrjconfig.commoneditors.PositionalDeviceEditor"/>
      <dependencies>
         <bean>ConfigBroker</bean>
         <jar path="${JCCL_BASE_DIR}/${JCCL_DATA_DIR}/beans">jccl_editors.jar</jar>
         <jar path="${VJ_BASE_DIR}/${TWEEK_DATA_DIR}/java">ui.jar</jar>
         <jar path="${VJ_BASE_DIR}/${VJ_DATA_DIR}/java">jogl-demos-data.jar</jar>
         <jar path="${VJ_BASE_DIR}/${VJ_DATA_DIR}/java">jogl-demos.jar</jar>
         <jar path="${VJ_BASE_DIR}/${VJ_DATA_DIR}/java">jogl-demos-util.jar</jar>
         <jar path="${VJ_BASE_DIR}/${VJ_DATA_DIR}/java">jogl.jar</jar>
      </dependencies>
   </service>
</beanlist>

=== rpavlik/vrjuggler-2.2-debs/modules/tweek/extensions/java/WizardBuilder.xml
<?xml version="1.0" encoding="UTF-8"?>
<beanlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="http://www.vrjuggler.org/tweek/xsd/1.1/beanlist.xsd">
   <guipanel name="WizardBuilder">
      <file name="${TWEEK_BASE_DIR}/${TWEEK_DATA_DIR}/beans/WizardBuilder.jar"
            class="org.vrjuggler.tweek.wizard.builder.WizardBuilder" />
      <dependencies>
         <bean>ConfigBroker</bean>
         <jar path="${TWEEK_BASE_DIR}/${JCCL_DATA_DIR}/beans">jccl_editors.jar</jar>
         <jar path="${TWEEK_BASE_DIR}/${TWEEK_DATA_DIR}/java">ui.jar</jar>
         <jar path="${TWEEK_BASE_DIR}/${TWEEK_DATA_DIR}/java">wizard.jar</jar>
         <jar path="${VJ_BASE_DIR}/${VRJ_DATA_DIR}/java">Devices.jar</jar>
         <jar path="${VJ_BASE_DIR}/${VRJ_DATA_DIR}/java">ClusterWizard.jar</jar>
         <jar path="${VJ_BASE_DIR}/${VRJ_DATA_DIR}/java">Simulator.jar</jar>
         <jar path="${VJ_BASE_DIR}/${VRJ_DATA_DIR}/java">NewDevice.jar</jar>
      </dependencies>
      <tree path="/Wizards/" />
   </guipanel>
</beanlist>

=== rpavlik/vrjuggler-2.2-debs/modules/vrjuggler/vrjconfig/customeditors/surfacedisplayeditor/SurfaceDisplayEditor.xml
<?xml version="1.0" encoding="UTF-8"?>
<beanlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="http://www.vrjuggler.org/tweek/xsd/1.1/beanlist.xsd">
   <generic name="SurfaceDisplayEditor">
      <file name="${VJ_BASE_DIR}/${VJ_DATA_DIR}/beans/customeditors/SurfaceDisplayEditor.jar"
            class="org.vrjuggler.vrjconfig.customeditors.surfacedisplayeditor.SurfaceDisplayEditor"/>
      <dependencies>
         <bean>ConfigBroker</bean>
         <jar path="${JCCL_BASE_DIR}/${JCCL_DATA_DIR}/beans">jccl_editors.jar</jar>
         <jar path="${JCCL_BASE_DIR}/${JCCL_DATA_DIR}/java">TableLayout.jar</jar>
         <jar path="${TWEEK_BASE_DIR}/${TWEEK_DATA_DIR}/java">ui.jar</jar>
      </dependencies>
   </generic>
</beanlist>
